layout: stacked
style: dark

repository: girishcodealchemy/githubaction-runtime-adhoc-pr-commands

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-mermaid
  - jekyll-paginate

mermaid:
  src: '/docs/assets/mermaid-10.8.0/mermaid.min.js'


social_media:
  website: https://girishcodealcehmy.github.io
  linkedin: vgirish10