layout: sidebar
style: light

plugins:
  - jekyll-mermaid

mermaid:
  src: '/docs/assets/mermaid-10.8.0/mermaid.min.js'


social_media:
  website: https://girishcodealcehmy.github.io
  linkedin: vgirish10